server:
  port: 7000
spring:
  application:
    name: eureka-server
  profiles:
    active: dev
---
spring:
  profiles: dev
  security:
    user:
      name: root  # 配置登录的账号是root
      password: root #配置登录的密码是root
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
---
spring:
  profiles: test
  security:
    user:
      name: root  # 配置登录的账号是root
      password: root #配置登录的密码是root
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
