version: '2'
services:
  consul-server:
    restart: always
    container_name: consul-server
    image: consul
    ports:
      - 8500:8500
    networks:
      - springCloud-consul
    volumes:
      - /opt/docker/consul/data:/consul/data

  spring-cloud-gateway:
    restart: always
    container_name: spring-cloud-gateway
    image: registry.cn-hangzhou.aliyuncs.com/ldbmcs/spring-cloud-gateway
    ports:
      - 7014:7014
    networks:
      - springCloud-consul
    volumes:
      - /home/spring-cloud-examples/spring-cloud-gateway/log:/app/log/
    depends_on:
      - consul-server

  spring-boot-admin:
    restart: always
    container_name: spring-boot-admin
    image: registry.cn-hangzhou.aliyuncs.com/ldbmcs/spring-boot-admin
    ports:
      - 7015:7015
    networks:
      - springCloud-consul
    volumes:
      - /home/spring-cloud-examples/spring-boot-admin/log:/app/log/
    depends_on:
      - consul-server

  spring-cloud-consul-consumer:
    restart: always
    container_name: spring-cloud-consul-consumer
    image: registry.cn-hangzhou.aliyuncs.com/ldbmcs/spring-cloud-consul-consumer
    ports:
      - 7012:7012
    networks:
      - springCloud-consul
    volumes:
      - /home/spring-cloud-examples/spring-cloud-consul-consumer/log:/app/log/
    depends_on:
      - consul-server

  spring-cloud-consul-producer:
    restart: always
    container_name: spring-cloud-consul-producer
    image: registry.cn-hangzhou.aliyuncs.com/ldbmcs/spring-cloud-consul-producer
    ports:
      - 7013:7013
    networks:
      - springCloud-consul
    volumes:
      - /home/spring-cloud-examples/spring-cloud-consul-producer/log:/app/log/
    depends_on:
      - consul-server

# 构建网络环境
networks:
  springCloud-consul:
    driver: bridge