version: '2'
services:
  # 自定义服务名
  spring-cloud-eureka1:
    # 总起重启
    restart: always
    # 别名
    container_name: spring-cloud-eureka1
    # 编译DockerFile所在路径
    build: spring-cloud-eureka
    # 环境变量
    environment:
      SPRING_PROFILES_ACTIVE: dev
    # 端口映射
    ports:
      - 7000:7000
    # 挂载目录
    volumes:
      - /home/spring-cloud-examples/spring-cloud-eureka/log1:/app/log/
    # 网络桥接
    networks:
      - springCloud

  spring-cloud-config:
    restart: always
    container_name: spring-cloud-config
    build: spring-cloud-config
    environment:
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - 7005:7001
    networks:
      - springCloud
    volumes:
      - /home/spring-cloud-examples/spring-cloud-config/log:/app/log/
    # 等待某服务启动后启动服务
    depends_on:
      - spring-cloud-eureka1
    links:
      - spring-cloud-eureka1

# 构建网络环境    
networks:
  springCloud:
    driver: bridge
