server:
  port: 7001
spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  application:
    name: spring-cloud-producer
  cloud:
    config:
      name: spring-cloud-producer
      profile: dev
      label: master
      uri: http://123.206.196.94:7001 #指定使用ip访问配置中心